name: appimage

on: [push, pull_request, workflow_dispatch]


permissions:
  contents: write

jobs:
  appimage:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare the system
      run: |
        sudo apt update -y
        sudo apt install -y desktop-file-utils libfuse2

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build
      run: |
        bash pkg2appimage recipes/Unar.yml

    - run: echo "rev=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: 'out/*.AppImage'
        tag_name: 1.10.1

